services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=curso_springboot'
      - 'POSTGRES_PASSWORD=a1b2c3d4'
      - 'POSTGRES_USER=devdb'
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U devdb -d curso_springboot"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - '5432'
    networks:
      - red-backend-app

  cliente-service:
    image: 'alvarosalazar/cliente-service:latest'
    ports:
      - '8080:8080'
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_URL: jdbc:postgresql://postgres/curso_springboot
      DB_USERNAME: devdb
      DB_PASSWORD: a1b2c3d4
      JPA_DDL: create-drop
    profiles:
      - app
    networks:
      - red-backend-app

networks:
  red-backend-app:
    driver: bridge